if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
   set fileencodings=utf-8,latin1
endif

"自动缩进
set autoindent
"智能对齐
set smartindent
set tabstop=4
set softtabstop=4
"TAB4个空格
set shiftwidth=4
"搜索不区分大小写
set ignorecase
"智能搜索
set incsearch

set expandtab
